//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Eugen (WebDucer) Richter")]
[assembly: AssemblyCopyright("MIT - (c) 2019 Eugen [WebDucer] Richter")]

// Metadata Attributes
[assembly: AssemblyMetadata("git_hash", "0ae2e8dbfa0d2371a6b99145630c12943195cb3a")]
[assembly: AssemblyMetadata("sem_ver", "0.1.0-start-project.6")]
[assembly: AssemblyMetadata("build_date", "2019-01-16")]
